# Generated by Django 3.2.5 on 2021-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
