# Generated by Django 3.2.5 on 2021-07-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_feed_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
